### ISSUE TITLE
non of the command work on 2014 forester

### ISSUE THREAD

**Issue by estornino** [afreiday/2016-wrx-can-ids#2]
thanks for sharing Freiday.
I was thinking it can also work on 2014 Forester
I tried it following way, not working on my forester:

$ cansend can0 152#0000000000000010
$ cansend can0 152#0000000000000000
$ cansend can0 152#0000000000000020
$ cansend can0 152#0000000000000000
$ cansend can0 002#0101000000000000
$ cansend can0 002#0103000000000000
$ cansend can0 002#01f3000000000000
$ cansend can0 002#19fe000000000000
$ cansend can0 002#19fe000000000000
$ cansend can0 002#fffe000000000000
$ cansend can0 002#fffe000000000000
$ cansend can0 375#0000000000000000
$ cansend can0 002#fffe000000000000
$ cansend can0 375#0000000000000000
$ cansend can0 375#0300000000000000
$ cansend can0 140#0000000000ff0000
$ cansend can0 152#000000000000000c
...
$ cansend can0 281#2000000000000000

$ ifconfig
can0: flags=193<UP,RUNNING,NOARP>  mtu 16
        unspec 00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00  txqueuelen 10  (UNSPEC)
        RX packets 1262072  bytes 9611327 (9.6 MB)
        RX errors 21  dropped 28122  overruns 0  frame 0
        TX packets 24  bytes 192 (192.0 B)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

....

try to figure out how do you get those command on your wrx; 
are you using the command like `cansniffer -c can0` to monitor the screen changes everytime you operate different devices on car?   
there 're many digits keep changing even you didn't touch any thing on car...

any suggestions? appreciate it.

**Comment by afreiday** [comment]
I don't know necessarily that I can help with your specific car or what those commands do that you're trying to send. But I am using the `cansniffer` to monitor changes. 

You may want to check out [The Car Hacker's Handbook](http://docs.alexomar.com/biblioteca/thecarhackershandbook.pdf), specifically chapter 5, and maybe playing around with the instrument cluster simulator (also discussed in the chapter) to get some practice.

Cheers,

Andrew

**Comment by estornino** [comment]
thank you,  it's actually my mistake, the cmd need to be send out continuously....
really appreciate for your sharing.
